/* groovylint-disable CompileStatic */
pipeline {
    agent { node { label 'padrao' } }
  stages {
      stage('build and push dispatch') {
        steps{
                sh '''
                    pwd
                    cd dispatch
                    docker build -t hpjrvs/dispatch .
                    docker push hpjrvs/dispatch'''
            
        }
      }
    }
  }