pipeline {
	agent none
  stages {
    checkout scm
  	stage('build docker images') {
    	agent {
      	docker {
        	image 'maven:3.5.0'
        }
      }
      steps {
      	sh 'mvn clean install'
      }
    }
  }
}