pipeline {
	agent none
    
  stages {
    stage('Checkout SCM') {
    	agent {
      	any {
            checkout scm
        }
      }
  	stage('build and push dispatch') {
    	agent {
      	any {
            label 'labelName'
        }
      }
      steps {
        sh '''
        pwd
        cd dispatch
        docker build -t hpjrvs/dispatch .
        docker push hpjrvs/dispatch'''
        
      }
    }
  }
}